spring: 
   profiles:
      active:
      - dev
---
spring:
   profiles: dev  #cs环境
   application: 
      name: microservicecloud-config-atguigu-dev
---
spring:
   profiles: test  #开发环境
   application: 
      name: microservicecloud-config-atguigu-test
